language: php
dist: precise # Supports PHP 5.3
php:
    - nightly
    - 7.4
    - 7.3
    - 7.2
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - 5.4
    - 5.3

before_script: composer install
script: vendor/bin/phpunit
